import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile, lstat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { verifyInputs, sha256 } from './inputs.mjs';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const args=process.argv.slice(2);
assert.ok(args.length===0 || (args.length===2 && args[0]==='--inputs'));
const buildReceipt=JSON.parse(await readFile(path.join(root,'out/build-inputs.json'),'utf8'));
const inputs=await verifyInputs(args.length ? path.resolve(args[1]) : buildReceipt.inputs.recordPath);
assert.deepEqual(inputs,buildReceipt.inputs,'package proof inputs differ from successful build');
const npm=process.env.npm_execpath;assert.ok(npm,'run through npm');
const runNpm=(args,cwd)=>execFileSync(process.execPath,[npm,...args],{cwd,encoding:'utf8',maxBuffer:16*1024*1024});
const scratch=await mkdtemp(path.join(tmpdir(),'superbee-windows-consumer-'));
try {
 await mkdir(path.join(root,'out'),{recursive:true});
 const [receipt]=JSON.parse(runNpm(['pack','--ignore-scripts','--json','--pack-destination',path.join(root,'out')],root));
 const files=receipt.files.map(row=>row.path);
 assert.ok(files.includes('dist/superbee-windows.mjs'));assert.ok(files.includes('dist/filesystem.mjs'));
 assert.ok(files.includes('SKILL.md'));assert.ok(files.some(file=>file.startsWith('references/')));
 for(const file of files) assert.ok(['package.json','README.md','LICENSE','NOTICE','SKILL.md'].includes(file)||file.startsWith('references/')||file.startsWith('dist/'),`unexpected tarball file ${file}`);
 assert.ok(!files.some(file=>file.includes('node_modules')||file.startsWith('src/')||file.endsWith('.tgz')));
 const tarball=path.join(root,'out',receipt.filename);
 await writeFile(path.join(scratch,'package.json'),JSON.stringify({name:'windows-standalone-proof',private:true,type:'module'}));
 const core=inputs.packages.find(pkg=>pkg.name==='@superbee/core');
 runNpm(['install','--ignore-scripts','--force','--no-audit','--no-fund','--no-package-lock','--no-save',core.file,tarball],scratch);
 assert.deepEqual((await readdir(path.join(scratch,'node_modules/@superbee'))).sort(),['core','windows-cli']);
 const installed=path.join(scratch,'node_modules/@superbee/windows-cli');
 assert.equal((await lstat(installed)).isSymbolicLink(),false);
 const manifest=JSON.parse(await readFile(path.join(installed,'package.json'),'utf8'));
 assert.equal(manifest.dependencies,undefined);assert.equal(manifest.private,true);assert.equal(manifest.version,'0.0.0');
 assert.deepEqual(manifest.bin,{'superbee-windows':'dist/superbee-windows.mjs'});
 const entry=path.join(installed,'dist/superbee-windows.mjs');
 assert.equal(execFileSync(process.execPath,[entry,'--version'],{cwd:scratch,encoding:'utf8'}).trim(),'0.0.0');
 await writeFile(path.join(scratch,'consumer.ts'),`import { createWindowsFilesystemHostPolicy, windowsFilesystemHostPolicy } from '@superbee/windows-cli/filesystem';\nimport { FilesystemBackend, createFilesystemRuntime, type FilesystemHostPolicy } from '@superbee/core/filesystem';\nconst policy: FilesystemHostPolicy = createWindowsFilesystemHostPolicy();\nvoid new FilesystemBackend('/typecheck-only', {hostPolicy:policy});\nvoid createFilesystemRuntime(windowsFilesystemHostPolicy);\n`);
 await writeFile(path.join(scratch,'tsconfig.json'),JSON.stringify({compilerOptions:{target:'ES2022',module:'NodeNext',moduleResolution:'NodeNext',strict:true,noEmit:true,skipLibCheck:false,types:['node'],typeRoots:[path.join(root,'node_modules/@types')]},include:['consumer.ts']}));
 execFileSync(process.execPath,[path.join(root,'node_modules/typescript/bin/tsc'),'-p','tsconfig.json'],{cwd:scratch,stdio:'inherit'});
 await writeFile(path.join(scratch,'inert.mjs'),`import assert from 'node:assert/strict';\nimport { readdirSync } from 'node:fs';\nconst before={cwd:process.cwd(),env:JSON.stringify(process.env),files:readdirSync('.').sort()};\nconst policy=await import('@superbee/windows-cli/filesystem');\nassert.equal(policy.windowsFilesystemHostPolicy.enforcePrivateMode,false);\nassert.deepEqual({cwd:process.cwd(),env:JSON.stringify(process.env),files:readdirSync('.').sort()},before);\n`);
 const inert=execFileSync(process.execPath,['inert.mjs'],{cwd:scratch,encoding:'utf8',stdio:['ignore','pipe','pipe']});assert.equal(inert,'');
 const filesystemBytes=await readFile(path.join(installed,'dist/filesystem.mjs'),'utf8');
 assert.doesNotMatch(filesystemBytes,/@superbee\/cli|createCliRuntime|process\.argv|runManagedUiWorker/);
 const proof={tarball:receipt.filename,sha256:sha256(await readFile(tarball)),cliSource:inputs.provenance,scenarios:['file-allowlist','distinct-bin','no-runtime-dependencies','packed-core-type-contract','filesystem-import-inert']};
 await writeFile(path.join(root,'out/package-proof.json'),JSON.stringify(proof,null,2)+'\n');
 process.stdout.write(JSON.stringify(proof)+'\n');
} finally {await rm(scratch,{recursive:true,force:true,maxRetries:10,retryDelay:100});}
